<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jd.live</groupId>
        <artifactId>joylive-service</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>joylive-service-istio</artifactId>
    <properties>
        <package.plugin.type>plugin</package.plugin.type>
        <spring.cloud.version>3.1.8</spring.cloud.version>
        <spring-web.version>5.3.31</spring-web.version>
        <grpc.version>1.62.2</grpc.version>
        <envoy.controlplane.version>1.0.47</envoy.controlplane.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.jd.live</groupId>
            <artifactId>joylive-governance-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.jd.live</groupId>
            <artifactId>joylive-logger-slf4j</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
            <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
            <version>${spring.cloud.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-loadbalancer</artifactId>
            <version>${spring.cloud.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.glassfish</groupId>
                    <artifactId>jakarta.el</artifactId>
                </exclusion>
            </exclusions>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webflux</artifactId>
            <version>${spring-web.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>io.envoyproxy.controlplane</groupId>
            <artifactId>api</artifactId>
            <version>${envoy.controlplane.version}</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>${grpc.version}</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>${grpc.version}</version>
        </dependency>  
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>io.envoyproxy.controlplane:api</include>
                                    <include>com.google.protobuf:protobuf-java</include>
                                    <include>io.grpc:grpc-netty-shaded</include>
                                    <include>com.google.guava:guava</include>
                                    <include>com.google.guava:failureaccess</include>
                                    <include>com.google.guava:listenablefuture</include>
                                    <include>org.checkerframework:checker-qual</include>
                                    <include>com.google.j2objc:j2objc-annotations</include>
                                    <include>com.google.errorprone:error_prone_annotations</include>
                                    <include>io.grpc:grpc-core</include>
                                    <include>io.grpc:grpc-protobuf</include>
                                    <include>io.grpc:grpc-api</include>
                                    <include>io.grpc:grpc-context</include>
                                    <include>com.google.code.findbugs:jsr305</include>
                                    <include>com.google.api.grpc:proto-google-common-protos</include>
                                    <include>io.grpc:grpc-protobuf-lite</include>
                                    <include>io.grpc:grpc-stub</include>
                                    <include>io.perfmark:perfmark-api</include>
                                    <include>io.grpc:grpc-util</include>
                                    <include>org.codehaus.mojo:animal-sniffer-annotations</include>
                                    <include>com.google.code.gson:gson</include>
                                    <include>com.google.android:annotations</include>
                                </includes>
                            </artifactSet>
                            <transformers>
                                <!-- This transformer will merge the contents of META-INF/services -->
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                            <relocations>
                                <relocation>
                                    <pattern>io.envoyproxy.controlplane</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.io.envoyproxy.controlplane</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.protobuf</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.com.google.protobuf</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.grpc</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.io.grpc</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.guava</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.com.google.guava</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.checkerframework</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.org.checkerframework</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.j2objc</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.com.google.j2objc</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.errorprone</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.com.google.errorprone</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.code.findbugs</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.com.google.code.findbugs</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.api.grpc</pattern>
                                    <shadedPattern>com.jd.live.agent.shaded.com.google.api.grpc</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>